### PR TITLE
mplayer support

### PR DESCRIPTION
**Pull request by AndrewRadev**
This is super great work, but I don't have `afplay` on my linux system. Mplayer seems to work. 

I'd also consider doing the `system` dance with nulled out and err while actually calling, since mplayer prints a bunch of output, but that might actually be useful, who knows.

### CODE REVIEW

**Comment by JonRowe** [comment]
Honk!

Yeah nulling out the stdout/err for mplayer would seem useful then, theres a test honker that uses this. I mean its all for fun so I'm not that bothered :)

**Comment by AndrewRadev** [comment]
Silenced the output, then, honking shouldn't print stuff to the console anymore.

**Comment by JonRowe** [comment]
Honk!

**Comment by JonRowe** [comment]
Released as 0.0.2

**Pull request merged**
